routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\FrontendPageController;
use App\Http\Controllers\Admin\CounterController;
use App\Http\Controllers\Admin\AdminAuthController;
use App\Http\Controllers\Admin\AdminPageController;
use App\Http\Controllers\Admin\PortfolioController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\Admin\PostcategoryController;
use App\Http\Controllers\Admin\PortfolioCategoryController;


// admin auth routes
    Route::group(['middleware' => 'admin.redirect'], function(){
    Route::get('/admin-login' , [ AdminAuthController::class, 'showLoginPage' ]) -> name('admin.login.page');
    Route::post('/admin-login' , [ AdminAuthController::class, 'login' ]) -> name('admin.login');
}); 
// admin page routes user login chara ei dashboard access korte parbe na
    Route::group([ 'middleware' => 'admin' ], function(){ //ei route gula admin middleware er under e
    Route::get('/dashboard' , [ AdminPageController::class, 'showDashboard' ]) -> name('admin.dashboard');
    Route::get('/admin-logout' , [ AdminAuthController::class, 'logout' ]) -> name('admin.logout');
    // permission routes 
    Route::resource('/permission', PermissionController::class);
    // Roles routes 
    Route::resource('/role', RoleController::class);
    // Roles routes 
    Route::resource('/admin-user', AdminController::class);
    Route::get('/admin-user-status-update/{id}', [ AdminController::class, 'updateStatus' ]) -> name('admin.status.update');
    Route::get('/admin-user-trash-update/{id}', [ AdminController::class, 'updateTrash' ]) -> name('admin.trash.update');
    Route::get('/admin-trash', [ AdminController::class, 'trashUsers' ]) -> name('admin.trash');
    
    // slider routes 
    Route::resource('/slider', SliderController::class);
    Route::resource('/testimonial', TestimonialController::class);
    Route::resource('/client', ClientController::class);
    Route::resource('/counter', CounterController::class);
    Route::resource('/portfolio-category', PortfolioCategoryController::class);
    Route::resource('/portfolio', PortfolioController::class);
    Route::resource('/tag', TagController::class);
    Route::resource('/post-category', PostcategoryController::class);
    Route::resource('/post', PostController::class);   
});

/**
 * Frontend Routes  
 */
    Route::get('/', [ FrontendPageController::class, 'showHomePage' ]) -> name('home.page');
    Route::get('/blog', [ FrontendPageController::class, 'showBlogPage' ]) -> name('blog.page');
    Route::get('/contact', [ FrontendPageController::class, 'showContactPage' ]) -> name('contact.page');
    Route::get('/portfolio-single/{slug}', [ FrontendPageController::class, 'showSinglePortfolioPage' ]) -> name('portfolio.single.page');

resources/views/admin/pages/user/index.blade.php
@extends('admin.layouts.app')

@section('main-section')

<div class="row">
    <div class="col-lg-8">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h4 class="card-title">All Admin users</h4>
                <a href="{{ route('admin.trash') }}" class="text-danger">Trash users <i class="fa fa-arrow-right"></i></a>
            </div>
            <div class="card-body">
                @include('validate-main')
                <div class="table-responsive">
                    <table class="table mb-0 data-table-haq">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Role</th>
                                <th>Photo</th>
                                <th>Created At</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @forelse ($all_admin as $item)
                                
                                @if($item -> name !== 'Provider')

                                    <tr>
                                        <td>{{ $loop -> index + 1 }}</td>
                                        <td>{{ $item -> name }}</td>
                                        <td>{{ $item -> role -> name }}</td>
                                        <td>                              
                                            @if($item -> photo == 'avatar.png')
                                                <img style="width:60px;height:60px;object-fit:cover;" src="{{ url('storage/admins/man.jpg') }}" alt="">
                                            @endif
                                        </td>
                                        <td>{{ $item -> created_at -> diffForHumans() }}</td>
                                        <td>
                                            @if($item -> status )
                                                <span class="badge badge-success">Active User</span>
                                                <a class="text-danger" href="{{ route('admin.status.update', $item -> id ) }}"><i class="fa fa-times"></i></a>
                                            @else 
                                                <span class="badge badge-danger">Blocked User</span>
                                                <a class="text-success" href="{{ route('admin.status.update', $item -> id ) }}"><i class="fa fa-check"></i></a>
                                            @endif
                                        </td>
                                        <td>
                                            {{-- <a class="btn btn-sm btn-info" href="#"><i class="fa fa-eye"></i></a> --}}
                                            

                                            <a class="btn btn-sm btn-warning" href="{{ route('permission.edit', $item -> id ) }}"><i class="fa fa-edit"></i></a>
                                            <a href="{{ route('admin.trash.update', $item -> id) }}" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></a>

                                            {{-- <form action="{{ route('permission.destroy', $item -> id ) }}" class="d-inline delete-form" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-sm btn-danger" type="submit"><i class="fa fa-trash"></i></button>
                                            </form> --}}
                                        </td>
                                    </tr>

                                @endif

                            @empty
                                <tr>
                                    <td colspan="5" class="text-center text-danger">No records found</td>
                                </tr>
                            @endforelse

                           
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">

        @if( $form_type == 'create' )
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Add new User</h4>
            </div>
            <div class="card-body">
                @include('validate')
                <form action="{{ route('admin-user.store') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label>Name</label>
                        <input name="name" type="text" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Email</label>
                        <input name="email" type="text" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Username</label>
                        <input name="username" type="text" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Cell</label>
                        <input name="cell" type="text" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Role</label>
                        <select name="role" id="" class="form-control">
                            <option value="">-select-</option>
                            @foreach( $roles as $role )
                                <option value="{{ $role -> id }}">{{ $role -> name }}</option>
                            @endforeach
                        </select>
                    </div>

                    
                
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        @endif

        @if( $form_type == 'edit' )
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h4 class="card-title">Edit User</h4>
                <a href="{{ route('admin-user.index') }}">back</a>
            </div>
            <div class="card-body">
                @include('validate')
                <form action="{{ route('admin-user.update', $edit-> id ) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label>Name</label>
                        <input name="name" value="{{ $edit-> name }}" type="text" class="form-control">
                    </div>
                
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        @endif

    </div>
</div>


@endsection 

resources/views/admin/pages/user/trash.blade.php
@extends('admin.layouts.app')

@section('main-section')

<div class="row">
    <div class="col-lg-8">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h4 class="card-title">All Admin Trash users</h4>
                <a href="{{ route('admin-user.index') }}" class="text-success">Published users <i class="fa fa-arrow-right"></i></a>
            </div>
            <div class="card-body">
                @include('validate-main')
                <div class="table-responsive">
                    <table class="table mb-0">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Photo</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @forelse ($all_admin as $item)
                                
                                @if($item -> name !== 'Provider')

                                    <tr>
                                        <td>{{ $loop -> index + 1 }}</td>
                                        <td>{{ $item -> name }}</td>
                                        <td>                              
                                            @if($item -> photo == 'avatar.png')
                                                <img style="width:60px;height:60px;object-fit:cover;" src="{{ url('storage/admins/avatar.png') }}" alt="">
                                            @endif
                                        </td>
                                        <td>
                                            {{-- <a class="btn btn-sm btn-info" href="#"><i class="fa fa-eye"></i></a> --}}
                                            
                                            <a href="{{ route('admin.trash.update', $item -> id) }}" class="btn btn-sm btn-info">Restore User</a>

                                            <form action="{{ route('admin-user.destroy', $item -> id ) }}" class="d-inline delete-form" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-sm btn-danger" type="submit">Delete Permanently</button>
                                            </form>
                                        </td>
                                    </tr>

                                @endif

                            @empty
                                <tr>
                                    <td colspan="5" class="text-center text-danger">No records found</td>
                                </tr>
                            @endforelse

                           
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">

        @if( $form_type == 'create' )
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Add new User</h4>
            </div>
            <div class="card-body">
                @include('validate')
                <form action="{{ route('admin-user.store') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label>Name</label>
                        <input name="name" type="text" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Email</label>
                        <input name="email" type="text" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Username</label>
                        <input name="username" type="text" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Cell</label>
                        <input name="cell" type="text" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Role</label>
                        <select name="role" id="" class="form-control">
                            <option value="">-select-</option>
                            @foreach( $roles as $role )
                                <option value="{{ $role -> id }}">{{ $role -> name }}</option>
                            @endforeach
                        </select>
                    </div>

                    
                
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        @endif

        {{-- @if( $form_type == 'edit' )
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h4 class="card-title">Edit Permission</h4>
                <a href="{{ route('permission.index') }}">back</a>
            </div>
            <div class="card-body">
                @include('validate')
                <form action="{{ route('permission.update', $edit-> id ) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label>Name</label>
                        <input name="name" value="{{ $edit-> name }}" type="text" class="form-control">
                    </div>
                
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        @endif --}}

    </div>
</div>


@endsection 