routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\FrontendPageController;
use App\Http\Controllers\Admin\CounterController;
use App\Http\Controllers\Admin\AdminAuthController;
use App\Http\Controllers\Admin\AdminPageController;
use App\Http\Controllers\Admin\PortfolioController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\Admin\PostcategoryController;
use App\Http\Controllers\Admin\PortfolioCategoryController;


// admin auth routes
    Route::group(['middleware' => 'admin.redirect'], function(){
    Route::get('/admin-login' , [ AdminAuthController::class, 'showLoginPage' ]) -> name('admin.login.page');
    Route::post('/admin-login' , [ AdminAuthController::class, 'login' ]) -> name('admin.login');
}); 
// admin page routes user login chara ei dashboard access korte parbe na
    Route::group([ 'middleware' => 'admin' ], function(){ //ei route gula admin middleware er under e
    Route::get('/dashboard' , [ AdminPageController::class, 'showDashboard' ]) -> name('admin.dashboard');
    Route::get('/admin-logout' , [ AdminAuthController::class, 'logout' ]) -> name('admin.logout');
    // permission routes 
    Route::resource('/permission', PermissionController::class);
    // Roles routes 
    Route::resource('/role', RoleController::class);
    // Roles routes 
    Route::resource('/admin-user', AdminController::class);
    Route::get('/admin-user-status-update/{id}', [ AdminController::class, 'updateStatus' ]) -> name('admin.status.update');
    Route::get('/admin-user-trash-update/{id}', [ AdminController::class, 'updateTrash' ]) -> name('admin.trash.update');
    Route::get('/admin-trash', [ AdminController::class, 'trashUsers' ]) -> name('admin.trash');
    
    // slider routes 
    Route::resource('/slider', SliderController::class);
    Route::resource('/testimonial', TestimonialController::class);
    Route::resource('/client', ClientController::class);
    Route::resource('/counter', CounterController::class);
    Route::resource('/portfolio-category', PortfolioCategoryController::class);
    Route::resource('/portfolio', PortfolioController::class);
    Route::resource('/tag', TagController::class);
    Route::resource('/post-category', PostcategoryController::class);
    Route::resource('/post', PostController::class);   
});

/**
 * Frontend Routes  
 */
    Route::get('/', [ FrontendPageController::class, 'showHomePage' ]) -> name('home.page');
    Route::get('/blog', [ FrontendPageController::class, 'showBlogPage' ]) -> name('blog.page');
    Route::get('/contact', [ FrontendPageController::class, 'showContactPage' ]) -> name('contact.page');
    Route::get('/portfolio-single/{slug}', [ FrontendPageController::class, 'showSinglePortfolioPage' ]) -> name('portfolio.single.page');

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;

    protected $guarded = [];
}

resources/views/admin/pages/client/index.blade.php
@extends('admin.layouts.app')

@section('main-section')

<div class="row">
    <div class="col-lg-8">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h4 class="card-title">All Clients</h4>
                <a href="{{ route('admin.trash') }}" class="text-danger">Trash users <i class="fa fa-arrow-right"></i></a>
            </div>
            <div class="card-body">
                @include('validate-main')
                <div class="table-responsive">
                    <table class="table mb-0 data-table-haq">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>client</th>
                                <th>Logo</th>
                                <th>Created At</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($clients as $item)
                                <tr>
                                    <td>{{ $loop -> index + 1 }}</td>
                                    <td>{{ $item -> name }}</td>
                                    <td><img style="width: 60px ; height:60px; object-fit:cover; " src="{{ url( 'storage/clients/' . $item -> logo) }}" alt=""></td>
                                    <td>{{ $item -> created_at -> diffForHumans() }}</td>
                                    <td>
                                        @if($item -> status )
                                                <span class="badge badge-success">Published</span>
                                                <a class="text-danger" href="{{ route('admin.status.update', $item -> id ) }}"><i class="fa fa-times"></i></a>
                                        @else 
                                            <span class="badge badge-danger">unpublished</span>
                                            <a class="text-success" href="{{ route('admin.status.update', $item -> id ) }}"><i class="fa fa-check"></i></a>
                                        @endif    
                                    </td>
                                    <td>
                                        <a class="btn btn-sm btn-warning" href="{{ route('slider.edit', $item -> id ) }}"><i class="fa fa-edit"></i></a>
                                        
                                        <a href="{{ route('admin.trash.update', $item -> id) }}" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></a>

                                    </td>
                                </tr>
                            @empty
                                
                            @endforelse

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">

        @if( $form_type == 'create')
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Add new Testimonial</h4>
            </div>
            <div class="card-body">
                @include('validate')
                <form action="{{ route('client.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label>Client name</label>
                        <input name="name" type="text" value="{{ old('name') }}" class="form-control">
                    </div>

                    <div class="form-group">
                        <label>Logo</label>
                        <br>
                        <br>
                        <img style="max-width:100%;" id="slider-photo-preview" src="" alt="">
                        <br>
                        <br>
                        <input style="display:none;" name="logo" type="file" class="form-control" id="slider-photo">
                        <label for="slider-photo">
                            <img style="width:100px; cursor:pointer;" src="https://icon-library.com/images/image-icon/image-icon-2.jpg" alt="">
                        </label>
                    </div>


                    
                
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        @endif





    </div>
</div>


@endsection 