routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\FrontendPageController;
use App\Http\Controllers\Admin\CounterController;
use App\Http\Controllers\Admin\AdminAuthController;
use App\Http\Controllers\Admin\AdminPageController;
use App\Http\Controllers\Admin\PortfolioController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\Admin\PostcategoryController;
use App\Http\Controllers\Admin\PortfolioCategoryController;


// admin auth routes
    Route::group(['middleware' => 'admin.redirect'], function(){
    Route::get('/admin-login' , [ AdminAuthController::class, 'showLoginPage' ]) -> name('admin.login.page');
    Route::post('/admin-login' , [ AdminAuthController::class, 'login' ]) -> name('admin.login');
}); 
// admin page routes user login chara ei dashboard access korte parbe na
    Route::group([ 'middleware' => 'admin' ], function(){ //ei route gula admin middleware er under e
    Route::get('/dashboard' , [ AdminPageController::class, 'showDashboard' ]) -> name('admin.dashboard');
    Route::get('/admin-logout' , [ AdminAuthController::class, 'logout' ]) -> name('admin.logout');
    // permission routes 
    Route::resource('/permission', PermissionController::class);
    // Roles routes 
    Route::resource('/role', RoleController::class);
    // Roles routes 
    Route::resource('/admin-user', AdminController::class);
    Route::get('/admin-user-status-update/{id}', [ AdminController::class, 'updateStatus' ]) -> name('admin.status.update');
    Route::get('/admin-user-trash-update/{id}', [ AdminController::class, 'updateTrash' ]) -> name('admin.trash.update');
    Route::get('/admin-trash', [ AdminController::class, 'trashUsers' ]) -> name('admin.trash');
    
    // slider routes 
    Route::resource('/slider', SliderController::class);
    Route::resource('/testimonial', TestimonialController::class);
    Route::resource('/client', ClientController::class);
    Route::resource('/counter', CounterController::class);
    Route::resource('/portfolio-category', PortfolioCategoryController::class);
    Route::resource('/portfolio', PortfolioController::class);
    Route::resource('/tag', TagController::class);
    Route::resource('/post-category', PostcategoryController::class);
    Route::resource('/post', PostController::class);   
});

/**
 * Frontend Routes  
 */
    Route::get('/', [ FrontendPageController::class, 'showHomePage' ]) -> name('home.page');
    Route::get('/blog', [ FrontendPageController::class, 'showBlogPage' ]) -> name('blog.page');
    Route::get('/contact', [ FrontendPageController::class, 'showContactPage' ]) -> name('contact.page');
    Route::get('/portfolio-single/{slug}', [ FrontendPageController::class, 'showSinglePortfolioPage' ]) -> name('portfolio.single.page');

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <title>Doccure - Dashboard</title>
		
		<!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="{{ asset('admin/assets/img/favicon.png') }}">
		
		<!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{{ asset('admin/assets/css/bootstrap.min.css') }}">
		
		<!-- Fontawesome CSS -->
        <link rel="stylesheet" href="{{ asset('admin/assets/css/font-awesome.min.css') }}">

		<link href="//cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
		
		<!-- Feathericon CSS -->
        <link rel="stylesheet" href="{{ asset('admin/assets/css/feathericon.min.css') }}">
		
		<link rel="stylesheet" href="{{ asset('admin/assets/plugins/morris/morris.css') }}">
		<link rel="stylesheet" href="{{ asset('admin/assets/icon/themify-icons.css') }}">

		
		<!-- Main CSS -->
        <link rel="stylesheet" href="{{ asset('admin/assets/css/style.css') }}">
		<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/v/bs4/dt-1.12.1/datatables.min.css"/>
 
		

		
		<!--[if lt IE 9]>
			<script src="admin/assets/js/html5shiv.min.js"></script>
			<script src="admin/assets/js/respond.min.js"></script>
		<![endif]-->
    </head>
    <body>
	
		<!-- Main Wrapper -->
        <div class="main-wrapper">
		
			@include('admin.layouts.header')

			@include('admin.layouts.sidebar')
			
			
			<!-- Page Wrapper -->
            <div class="page-wrapper">
			
                <div class="content container-fluid">
					
					<!-- Page Header -->
					<div class="page-header">
						<div class="row">
							<div class="col-sm-12">
								<h3 class="page-title">Welcome {{Auth::guard('admin')->user()->name}} !</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item active">Dashboard</li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /Page Header -->



					@section('main-section')
                    @show 
					
					
				</div>			
			</div>
			<!-- /Page Wrapper -->
		
        </div>
		<!-- /Main Wrapper -->
		
		<!-- jQuery -->
        <script src="{{ asset('admin/assets/js/jquery-3.2.1.min.js') }}"></script>
		
		<!-- Bootstrap Core JS -->
        <script src="{{ asset('admin/assets/js/popper.min.js') }}"></script>
        <script src="{{ asset('admin/assets/js/bootstrap.min.js') }}"></script>
		
		<!-- Slimscroll JS -->
        <script src="{{ asset('admin/assets/plugins/slimscroll/jquery.slimscroll.min.js') }}"></script>
		
		<script src="{{ asset('admin/assets/plugins/raphael/raphael.min.js') }}"></script>    
		<script src="{{ asset('admin/assets/plugins/morris/morris.min.js') }}"></script>  
		<script src="{{ asset('admin/assets/js/chart.morris.js') }}"></script>		
		<script src="//cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

		<script type="text/javascript" src="//cdn.datatables.net/v/bs4/dt-1.12.1/datatables.min.js"></script>
		<!-- Custom JS -->
		<script  src="{{ asset('admin/assets/ckeditor/ckeditor.js') }}"></script>
		<script  src="{{ asset('admin/assets/js/script.js') }}"></script>
		<script  src="{{ asset('custom/admin.js') }}"></script>
		
    </body>


</html>

resources/views/admin/layouts/header.blade.php
<!-- Header -->
<div class="header">
			
    <!-- Logo -->
    <div class="header-left">
        <a href="index.html" class="logo">
            <img src="{{asset('admin/assets/img/logo.png')}}" alt="Logo">
        </a>
        <a href="index.html" class="logo logo-small">
            <img src="{{asset('admin/assets/img/logo-small.png')}}" alt="Logo" width="30" height="30">
        </a>
    </div>
    <!-- /Logo -->
    
    <a href="javascript:void(0);" id="toggle_btn">
        <i class="fe fe-text-align-left"></i>
    </a>
    
    <div class="top-nav-search">
        <form>
            <input type="text" class="form-control" placeholder="Search here">
            <button class="btn" type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div>
    
    <!-- Mobile Menu Toggle -->
    <a class="mobile_btn" id="mobile_btn">
        <i class="fa fa-bars"></i>
    </a>
    <!-- /Mobile Menu Toggle -->
    
    <!-- Header Right Menu -->
    <ul class="nav user-menu">

        <!-- Notifications -->
        <li class="nav-item dropdown noti-dropdown">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                <i class="fe fe-bell"></i> <span class="badge badge-pill">3</span>
            </a>
            <div class="dropdown-menu notifications">
                <div class="topnav-dropdown-header">
                    <span class="notification-title">Notifications</span>
                    <a href="javascript:void(0)" class="clear-noti"> Clear All </a>
                </div>
                <div class="noti-content">
                    <ul class="notification-list">
                        <li class="notification-message">
                            <a href="#">
                                <div class="media">
                                    <span class="avatar avatar-sm">
                                        <img class="" alt="User Image" src="{{url('storage/admins' . Auth::guard('admin')->user()->photo)}}">
                                    </span>
                                    <div class="media-body">
                                        <p class="noti-details"><span class="noti-title">Dr. Ruby Perrin</span> Schedule <span class="noti-title">her appointment</span></p>
                                        <p class="noti-time"><span class="notification-time">4 mins ago</span></p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="notification-message">
                            <a href="#">
                                <div class="media">
                                    <span class="avatar avatar-sm">
                                        <img class="avatar-img rounded-circle" alt="User Image" src="{{url('storage/admins' . Auth::guard('admin')->user()->photo)}}">
                                    </span>
                                    <div class="media-body">
                                        <p class="noti-details"><span class="noti-title">Charlene Reed</span> has booked her appointment to <span class="noti-title">Dr. Ruby Perrin</span></p>
                                        <p class="noti-time"><span class="notification-time">6 mins ago</span></p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="notification-message">
                            <a href="#">
                                <div class="media">
                                    <span class="avatar avatar-sm">
                                        <img class="avatar-img rounded-circle" alt="User Image" src="{{asset('admin/assets/img/patients/patient2.jpg')}}">
                                    </span>
                                    <div class="media-body">
                                    <p class="noti-details"><span class="noti-title">Travis Trimble</span> sent a amount of $210 for his <span class="noti-title">appointment</span></p>
                                    <p class="noti-time"><span class="notification-time">8 mins ago</span></p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="notification-message">
                            <a href="#">
                                <div class="media">
                                    <span class="avatar avatar-sm">
                                        <img class="avatar-img rounded-circle" alt="User Image" src="admin/assets/img/patients/patient3.jpg">
                                    </span>
                                    <div class="media-body">
                                        <p class="noti-details"><span class="noti-title">Carl Kelly</span> send a message <span class="noti-title"> to his doctor</span></p>
                                        <p class="noti-time"><span class="notification-time">12 mins ago</span></p>
                                    </div>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="topnav-dropdown-footer">
                    <a href="#">View all Notifications</a>
                </div>
            </div>
        </li>
        <!-- /Notifications -->
        
        <!-- User Menu -->
        <li class="nav-item dropdown has-arrow">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                <span class="user-img"><img class="rounded-circle" src="admin/assets/img/profiles/avatar-01.jpg" width="31" alt="Ryan Taylor"></span>
            </a>
            <div class="dropdown-menu">
                <div class="user-header">
                    <div class="avatar avatar-sm">
                        <img src="admin/assets/img/profiles/avatar-01.jpg" alt="User Image" class="avatar-img rounded-circle">
                    </div>
                    <div class="user-text">
                        <h6>{{Auth::guard('admin')->user()->name}}</h6>
                        <p class="text-muted mb-0">{{Auth::guard('admin')->user()->role->name}}</p>
                    </div>
                </div>
                <a class="dropdown-item" href="profile.html">My Profile</a>
                <a class="dropdown-item" href="settings.html">Settings</a>
                <a class="dropdown-item" href="{{route('admin.logout')}}">Logout</a>
            </div>
        </li>
        <!-- /User Menu -->
        
    </ul>
    <!-- /Header Right Menu -->
    
</div>
<!-- /Header -->

resources/views/admin/layouts/sidebar.blade.php
			<!-- Sidebar -->
            <div class="sidebar" id="sidebar">
                <div class="sidebar-inner slimscroll">
					<div id="sidebar-menu" class="sidebar-menu">
						<ul>
							<li class="menu-title"> 
								<span>Main</span>
							</li>
							<li> 
								<a href="#"><i class="fe fe-home"></i> <span>Dashboard</span></a>
							</li>
							@if( in_array( 'Slider', json_decode(Auth::guard('admin') -> user() -> role -> permissions ) ) )
							<li> 
								<a href="{{ route('slider.index') }}"><i class="fe fe-home"></i> <span>Slider</span></a>
							</li>
							@endif
							@if( in_array( 'Testimonials', json_decode(Auth::guard('admin') -> user() -> role -> permissions ) ) )
							<li> 
								<a href="{{ route('testimonial.index') }}"><i class="fe fe-home"></i> <span>Testimonials</span></a>
							</li>
							@endif
							@if( in_array( 'Our Client', json_decode(Auth::guard('admin') -> user() -> role -> permissions ) ) )
							<li> 
								<a href="#"><i class="fe fe-home"></i> <span>Our Clients</span></a>
							</li>
							@endif

							@if( in_array( 'Counter', json_decode(Auth::guard('admin') -> user() -> role -> permissions ) ) )
							<li> 
								<a href="{{ route('counter.index') }}"><i class="fe fe-home"></i> <span>Counter</span></a>
							</li>
							@endif

							@if( in_array( 'Portfolio', json_decode(Auth::guard('admin') -> user() -> role -> permissions ) ) )
							<li class="submenu">
								<a href="#"><i class="fe fe-document"></i> <span> Portfolio</span> <span class="menu-arrow"></span></a>
								<ul style="display: none;">
									<li><a href="{{ route('portfolio.index') }}">Portfolio</a></li>
									<li><a href="{{ route('portfolio-category.index') }}">Category</a></li>
									
								</ul>
							</li>
							@endif

							@if( in_array( 'Our Team', json_decode(Auth::guard('admin') -> user() -> role -> permissions ) ) )
							<li> 
								<a href="#"><i class="fe fe-home"></i> <span>Our Team</span></a>
							</li>
							@endif
							
							@if( in_array( 'Posts', json_decode(Auth::guard('admin') -> user() -> role -> permissions ) ) )
							<li class="submenu">
								<a href="#"><i class="fe fe-document"></i> <span> Posts</span> <span class="menu-arrow"></span></a>
								<ul style="display: none;">
									<li><a href="{{ route('post.index') }}">All posts</a></li>
									<li><a href="{{ route('post-category.index') }}">Category</a></li>
									<li><a href="{{ route('tag.index') }}">Tags</a></li>
								</ul>
							</li>
							@endif


							@if( in_array( 'Users', json_decode(Auth::guard('admin') -> user() -> role -> permissions ) ) )
							<li class="menu-title"> 
								<span>Admin Options</span>
							</li>
							<li class="submenu">
								<a href="#"><i class="fe fe-document"></i> <span> Admin User</span> <span class="menu-arrow"></span></a>
								<ul style="display: none;">
									<li><a href="{{ route('admin-user.index') }}">Users</a></li>
									<li><a href="{{ route('role.index') }}">Role</a></li>
									<li><a href="{{ route('permission.index') }}">Permission</a></li>
								</ul>
							</li>
							@endif

							@if( in_array( 'Theme Options', json_decode(Auth::guard('admin') -> user() -> role -> permissions ) ) )
							<li> 
								<a href="#"><i class="fe fe-home"></i> <span>Theme Options</span></a>
							</li>
							@endif
							@if( in_array( 'Settings', json_decode(Auth::guard('admin') -> user() -> role -> permissions ) ) )
							<li> 
								<a href="#"><i class="fe fe-home"></i> <span>Settings</span></a>
							</li>
							@endif
							
						</ul>
					</div>
                </div>
            </div>
			<!-- /Sidebar -->