routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\FrontendPageController;
use App\Http\Controllers\Admin\CounterController;
use App\Http\Controllers\Admin\AdminAuthController;
use App\Http\Controllers\Admin\AdminPageController;
use App\Http\Controllers\Admin\PortfolioController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\Admin\PostcategoryController;
use App\Http\Controllers\Admin\PortfolioCategoryController;


// admin auth routes
    Route::group(['middleware' => 'admin.redirect'], function(){
    Route::get('/admin-login' , [ AdminAuthController::class, 'showLoginPage' ]) -> name('admin.login.page');
    Route::post('/admin-login' , [ AdminAuthController::class, 'login' ]) -> name('admin.login');
}); 
// admin page routes user login chara ei dashboard access korte parbe na
    Route::group([ 'middleware' => 'admin' ], function(){ //ei route gula admin middleware er under e
    Route::get('/dashboard' , [ AdminPageController::class, 'showDashboard' ]) -> name('admin.dashboard');
    Route::get('/admin-logout' , [ AdminAuthController::class, 'logout' ]) -> name('admin.logout');
    // permission routes 
    Route::resource('/permission', PermissionController::class);
    // Roles routes 
    Route::resource('/role', RoleController::class);
    // Roles routes 
    Route::resource('/admin-user', AdminController::class);
    Route::get('/admin-user-status-update/{id}', [ AdminController::class, 'updateStatus' ]) -> name('admin.status.update');
    Route::get('/admin-user-trash-update/{id}', [ AdminController::class, 'updateTrash' ]) -> name('admin.trash.update');
    Route::get('/admin-trash', [ AdminController::class, 'trashUsers' ]) -> name('admin.trash');
    
    // slider routes 
    Route::resource('/slider', SliderController::class);
    Route::resource('/testimonial', TestimonialController::class);
    Route::resource('/client', ClientController::class);
    Route::resource('/counter', CounterController::class);
    Route::resource('/portfolio-category', PortfolioCategoryController::class);
    Route::resource('/portfolio', PortfolioController::class);
    Route::resource('/tag', TagController::class);
    Route::resource('/post-category', PostcategoryController::class);
    Route::resource('/post', PostController::class);   
});

/**
 * Frontend Routes  
 */
    Route::get('/', [ FrontendPageController::class, 'showHomePage' ]) -> name('home.page');
    Route::get('/blog', [ FrontendPageController::class, 'showBlogPage' ]) -> name('blog.page');
    Route::get('/contact', [ FrontendPageController::class, 'showContactPage' ]) -> name('contact.page');
    Route::get('/portfolio-single/{slug}', [ FrontendPageController::class, 'showSinglePortfolioPage' ]) -> name('portfolio.single.page');

app/Models/permission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    use HasFactory;

    protected $guarded  = [];

    
    
}

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Permission;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = Permission::latest() -> get();
        return view('admin.pages.user.permission.index', [
            'all_permission' => $permissions,
            'form_type'      => 'create'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   

        // validation 
        $this -> validate( $request ,  [
            'name'      => 'required|unique:permissions'
        ]);

        // data store 
        Permission::create([
            'name'      => $request -> name,
            'slug'      => Str::slug($request -> name)
        ]);

        return back() -> with('success', 'Permission added successul');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permissions = Permission::latest() -> get();
        $per = Permission::findOrFail($id);
        return view('admin.pages.user.permission.index', [
            'all_permission' => $permissions,
            'form_type'      => 'edit',
            'edit'           => $per
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
       $update_data = Permission::findOrFail($id);
       $update_data -> update([
            'name'      => $request -> name,
            'slug'      => Str::slug($request -> name)
       ]);
       return back() -> with('success', 'Permission Updated successul');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $delete = Permission::findOrFail($id);
        $delete -> delete();
        return back() -> with('success-main', 'Permission deleted successul');

    }
}

resources/views/admin/pages/user/permission/index.blade.php
@extends('admin.layouts.app')

@section('main-section')

<div class="row">
    <div class="col-lg-8">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">All Permissions</h4>
            </div>
            <div class="card-body">
                @include('validate-main')
                <div class="table-responsive">
                    <table class="table mb-0 data-table-haq">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Slug</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @forelse ($all_permission as $per)
                                <tr>
                                    <td>{{ $loop -> index + 1 }}</td>
                                    <td>{{ $per -> name }}</td>
                                    <td>{{ $per -> slug }}</td>
                                    <td>{{ $per -> created_at -> diffForHumans() }}</td>
                                    <td>
                                        {{-- <a class="btn btn-sm btn-info" href="#"><i class="fa fa-eye"></i></a> --}}
                                        <a class="btn btn-sm btn-warning" href="{{ route('permission.edit', $per -> id ) }}"><i class="fa fa-edit"></i></a>
                                        <form action="{{ route('permission.destroy', $per -> id ) }}" class="d-inline delete-form" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-sm btn-danger" type="submit"><i class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5" class="text-center text-danger">No records found</td>
                                </tr>
                            @endforelse

                           
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">

        @if( $form_type == 'create' )
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Add new Permission</h4>
            </div>
            <div class="card-body">
                @include('validate')
                <form action="{{ route('permission.store') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label>Name</label>
                        <input name="name" type="text" class="form-control">
                    </div>
                
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        @endif

        @if( $form_type == 'edit' )
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h4 class="card-title">Edit Permission</h4>
                <a href="{{ route('permission.index') }}">back</a>
            </div>
            <div class="card-body">
                @include('validate')
                <form action="{{ route('permission.update', $edit-> id ) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label>Name</label>
                        <input name="name" value="{{ $edit-> name }}" type="text" class="form-control">
                    </div>
                
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        @endif

    </div>
</div>


@endsection 